#!/usr/bin/env python3
"""Run simulator smoke test from emitted textual ISA.

Expected textual forms:
  dma.load rd=2, base=0, size=2048, flag=0
  dma.load.mxu0 rd=1, base=2048, size=512, flag=0
  dma.wait flag=0
  matmul.mxu0 rd=0, rs1=2, rs2=1
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple

import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from npu_model.configs.hardware.default import DefaultHardwareConfig
from npu_model.configs.isa_definition import *  # noqa: F401,F403
from npu_model.configs.programs import *  # noqa: F401,F403
from npu_model.logging import LoggerConfig
from npu_model.simulation import Simulation
from npu_model.software.instruction import Instruction
from npu_model.software.program import Program


_LINE_RE = re.compile(r"^([a-zA-Z0-9_.]+)(?:\s+(.*))?$")
_KV_RE = re.compile(r"([a-zA-Z0-9_]+)\s*=\s*([+-]?[0-9]+)")


def parse_isa_lines(lines: List[str]) -> List[Instruction]:
    instructions: List[Instruction] = []
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = _LINE_RE.match(line)
        if not m:
            raise ValueError(f"Invalid ISA line: {line}")
        mnemonic = m.group(1)
        rest = m.group(2) or ""
        args = {k: int(v) for k, v in _KV_RE.findall(rest)}
        instructions.append(Instruction(mnemonic=mnemonic, args=args))
    return instructions


class _SmokeProgram(Program):
    instructions: List[Instruction] = []
    memory_regions: List[Tuple[int, torch.Tensor]] = []


def make_default_memory_regions() -> List[Tuple[int, torch.Tensor]]:
    # Matches the hard-coded skeleton generated by schedule->isa lowering.
    return [
        (0, torch.eye(64, 32, dtype=torch.float8_e4m3fn)),
        (2048, torch.eye(32, 16, dtype=torch.float8_e4m3fn)),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="Run simulator smoke test from textual ISA")
    parser.add_argument("isa_file", type=Path, help="Path to emitted textual ISA file")
    parser.add_argument("--max-cycles", type=int, default=10000)
    parser.add_argument("--program", type=str, help="Optional: Target program class name to use for numerical validation")
    args = parser.parse_args()

    lines = args.isa_file.read_text().splitlines()
    instructions = parse_isa_lines(lines)

    # Use program's memory regions if provided, otherwise use defaults
    reference_program = None
    if args.program:
        try:
            reference_program = eval(args.program)()
            _SmokeProgram.memory_regions = reference_program.memory_regions
        except NameError:
            _SmokeProgram.memory_regions = make_default_memory_regions()
    else:
        _SmokeProgram.memory_regions = make_default_memory_regions()

    _SmokeProgram.instructions = instructions

    sim = Simulation(
        hardware_config=DefaultHardwareConfig(),
        logger_config=LoggerConfig(filename=str(REPO_ROOT / "compiler" / "smoke_trace.json")),
        program=_SmokeProgram(),
    )
    sim.run(max_cycles=args.max_cycles)

    if sim.core.total_completed == 0:
        raise RuntimeError(
            "Smoke program made no forward progress (0 completed instructions). "
            "Increase max-cycles or verify emitted ISA."
        )

    # Check against golden result if reference program provided
    if reference_program and hasattr(reference_program, "golden_result") and reference_program.golden_result:
        print("Golden result provided - now performing correctness check:" + "\n")

        output_base, golden_tensor = reference_program.golden_result
        size = golden_tensor.numel() * golden_tensor.element_size()

        try:
            mem_data = sim.core.arch_state.read_memory(output_base, size)
            actual = mem_data.view(golden_tensor.dtype).reshape(golden_tensor.shape).clone()

            # Same logic as "scripts/test_programs.py"
            if torch.allclose(actual.float(), golden_tensor.float(), rtol=1e-2, atol=1e-2):
                max_diff = (actual.float() - golden_tensor.float()).abs().max()
                print(f"PASS - Compiler output matches reference!" + "\n")
                print(f"Max difference: {max_diff:.6e}")
            else:
                max_diff = (actual.float() - golden_tensor.float()).abs().max()
                mean_diff = (actual.float() - golden_tensor.float()).abs().mean()
                print(f"FAIL - Compiler output does NOT match!" + "\n")
                print(f"Max difference: {max_diff:.6e}" + "\n")
                print(f"Mean difference: {mean_diff:.6e}" + "\n")
                print(f"Observed first 16 elements from {hex(output_base)}): {mem_data.flatten()[:16]}" + "\n")
                print(f"Expected first 16 elements from {hex(output_base)}): {actual.flatten()[:16]}")
                return 1

        except Exception as e:
            print(f"Error during correctness check: {e}")
            return 1
    else:
        # No golden result provided. Print a deterministic snippet for CI/log inspection.
        snippet = sim.core.arch_state.read_mrf_bf16(0)[:2, :8]
        print("No golden result provided - fallback to default behavior:" + "\n")
        print("Smoke completed. MRF0[0:2,0:8]=")
        print(snippet)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
