#!/usr/bin/env python3
"""Run simulator smoke test from emitted textual ISA.

Expected textual forms:
  dma.load rd=2, base=0, size=2048, flag=0
  dma.load.mxu0 rd=1, base=2048, size=512, flag=0
  dma.wait flag=0
  matmul.mxu0 rd=0, rs1=2, rs2=1
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path
from typing import List, Tuple

import torch

REPO_ROOT = Path(__file__).resolve().parents[2]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from model_npu.configs.hardware.default import DefaultHardwareConfig
from model_npu.configs.isa_definition import *  # noqa: F401,F403
from model_npu.logging import LoggerConfig
from model_npu.simulation import Simulation
from model_npu.software.instruction import Instruction
from model_npu.software.program import Program


_LINE_RE = re.compile(r"^([a-zA-Z0-9_.]+)(?:\s+(.*))?$")
_KV_RE = re.compile(r"([a-zA-Z0-9_]+)\s*=\s*([+-]?[0-9]+)")


def parse_isa_lines(lines: List[str]) -> List[Instruction]:
    instructions: List[Instruction] = []
    for raw in lines:
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        m = _LINE_RE.match(line)
        if not m:
            raise ValueError(f"Invalid ISA line: {line}")
        mnemonic = m.group(1)
        rest = m.group(2) or ""
        args = {k: int(v) for k, v in _KV_RE.findall(rest)}
        instructions.append(Instruction(mnemonic=mnemonic, args=args))
    return instructions


class _SmokeProgram(Program):
    instructions: List[Instruction] = []
    memory_regions: List[Tuple[int, torch.Tensor]] = []


def make_default_memory_regions() -> List[Tuple[int, torch.Tensor]]:
    # Matches the hard-coded skeleton generated by schedule->isa lowering.
    return [
        (0, torch.eye(64, 32, dtype=torch.float8_e4m3fn)),
        (2048, torch.eye(32, 16, dtype=torch.float8_e4m3fn)),
    ]


def main() -> int:
    parser = argparse.ArgumentParser(description="Run simulator smoke test from textual ISA")
    parser.add_argument("isa_file", type=Path, help="Path to emitted textual ISA file")
    parser.add_argument("--max-cycles", type=int, default=10000)
    args = parser.parse_args()

    lines = args.isa_file.read_text().splitlines()
    instructions = parse_isa_lines(lines)

    _SmokeProgram.instructions = instructions
    _SmokeProgram.memory_regions = make_default_memory_regions()

    sim = Simulation(
        hardware_config=DefaultHardwareConfig(),
        logger_config=LoggerConfig(filename=str(REPO_ROOT / "compiler" / "smoke_trace.json")),
        program=_SmokeProgram(),
    )
    sim.run(max_cycles=args.max_cycles)

    if sim.core.total_completed == 0:
        raise RuntimeError(
            "Smoke program made no forward progress (0 completed instructions). "
            "Increase max-cycles or verify emitted ISA."
        )

    # Print a deterministic snippet for CI/log inspection.
    snippet = sim.core.arch_state.read_mrf_bf16(0)[:2, :8]
    print("Smoke completed. MRF0[0:2,0:8]=")
    print(snippet)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
