"""Integer datapaths from E4M3Mul, E4M3ProdAddBF16 and AnchorAccumulationTree,
plus the VPU's BF16 truncation and FP8 converters.

Unary BF16 tables are exhaustive outputs of the actual RTL, regenerated by
atlas.vector.NpuModelUnaryTableTest. Index and result are raw 16-bit encodings.
"""
from functools import lru_cache
from pathlib import Path
import gzip
import struct

import torch


@lru_cache(maxsize=None)
def _unary_table(name: str) -> torch.Tensor:
    data = gzip.decompress((Path(__file__).with_name('data') / f'{name}.bin.gz').read_bytes())
    assert len(data) == 65536 * 2
    return torch.tensor(struct.unpack('<65536H', data), dtype=torch.int32)


def unary(name: str, values: torch.Tensor) -> torch.Tensor:
    indices = values.contiguous().view(torch.int16).to(torch.int64) & 65535
    return _unary_table(name)[indices].to(torch.int16).view(torch.bfloat16)


def minmax(a: torch.Tensor, b: torch.Tensor, maximum: bool) -> torch.Tensor:
    """VectorParam's ordered-bit comparison (including NaN and signed zero)."""
    ar = a.contiguous().view(torch.int16).to(torch.int32) & 65535
    br = b.contiguous().view(torch.int16).to(torch.int32) & 65535
    ao = torch.where(ar & 32768 != 0, ar ^ 65535, ar ^ 32768)
    bo = torch.where(br & 32768 != 0, br ^ 65535, br ^ 32768)
    take_a = ao > bo if maximum else ao < bo
    return torch.where(take_a, ar, br).to(torch.int16).view(torch.bfloat16)


def extremum(values: torch.Tensor, dim: int, maximum: bool) -> torch.Tensor:
    """Reduce with minmax's ordering, which is total, so tree order is irrelevant."""
    raw = values.contiguous().view(torch.int16).to(torch.int32) & 65535
    ordered = torch.where(raw & 32768 != 0, raw ^ 65535, raw ^ 32768)
    index = ordered.argmax(dim, keepdim=True) if maximum else ordered.argmin(dim, keepdim=True)
    # Gather the raw bits: a BF16 gather canonicalizes NaN payloads.
    return values.contiguous().view(torch.int16).gather(dim, index).view(torch.bfloat16)


def _truncated_bf16(value: torch.Tensor) -> torch.Tensor:
    """AddSubSumVec/ColAddVec take the upper 16 bits of FP32 results."""
    raw = (value.float().contiguous().view(torch.int32) >> 16).to(torch.int16)
    # HardFloat emits its default positive quiet NaN, without input payloads.
    raw = torch.where(torch.isnan(value), 0x7FC0, raw).to(torch.int16)
    return raw.view(torch.bfloat16)


def pack_row(value: torch.Tensor, scale: int, *, mxu: bool = False) -> torch.Tensor:
    """Literal converters: VPU divides by the scale, MXU multiplies by it.

    BF16ScaleToE4M3 also emits 0x7f for rounded +480, whereas FP8Pack
    clamps that encoding to 0x7e. Preserve this RTL difference.
    """
    output = []
    shift = min(127, max(-128, int(scale) - 127))
    for raw in value.contiguous().view(torch.int16).tolist():
        raw &= 0xFFFF
        sign, exp, mant = raw >> 15, (raw >> 7) & 255, raw & 127
        if exp == 0 or (exp == 255 and mant):
            out = 0
        elif exp == 255:
            out = (sign << 7) | 0x7E
        else:
            adjusted = exp - 127 + (shift if mxu else -shift)
            sig = 128 | mant
            rounded = (sig >> 4) + int(bool((sig & 8) and ((sig & 7) or ((sig >> 4) & 1))))
            if rounded == 16:
                adjusted += 1
                rounded = 8
            frac = (rounded - 8) & 7
            if adjusted > 8 or (not mxu and adjusted == 8 and frac == 7):
                out = (sign << 7) | 0x7E
            elif adjusted < -6:
                out = 0
            else:
                out = (sign << 7) | ((adjusted + 7) << 3) | frac
        output.append(out)
    return torch.tensor(output, dtype=torch.uint8)


def unpack_row(value: torch.Tensor, scale: int) -> torch.Tensor:
    """FP8Unpack's E4M3/E8M0 conversion, preserving signed flushed zero."""
    output = []
    shift = min(127, max(-128, int(scale) - 127))
    for raw in value.tolist():
        sign, exp, mant = raw >> 7, (raw >> 3) & 15, raw & 7
        adjusted = exp - 7 + shift + 127
        if exp == 0 or (exp == 15 and mant == 7) or adjusted <= 0:
            out = sign << 15
        elif adjusted >= 255:
            out = (sign << 15) | 0x7F7F
        else:
            out = (sign << 15) | (adjusted << 7) | (mant << 4)
        output.append(out)
    return torch.tensor(output, dtype=torch.uint16).view(torch.bfloat16)


def product(a: int, b: int) -> tuple[int, int, int]:
    """E4M3Mul: sign, biased E5 exponent, seven fraction bits."""
    sign = (a ^ b) >> 7
    ae, be = (a >> 3) & 15, (b >> 3) & 15
    if not ae or not be:
        return sign, 0, 0
    sig = (8 | (a & 7)) * (8 | (b & 7))
    carry = sig >> 7
    return sign, ae + be - 1 + carry, (sig if carry else sig << 1) & 127


def fma_bits(a: int, b: int, addend: int) -> int:
    """Literal default SA custom FMA, with its shift-right-jam rounding."""
    ps, pe, pm = product(a, b)
    if pe == 0:
        return addend
    pe += 114
    ae, am, az = (addend >> 7) & 255, addend & 127, addend >> 15
    if ae == 0:
        return (ps << 15) | (pe << 7) | pm
    p, q = (128 | pm) << 3, (128 | am) << 3
    if (pe, p) >= (ae, q):
        e, diff, sign, other, big, small = pe, pe-ae, ps, az, p, q
    else:
        e, diff, sign, other, big, small = ae, ae-pe, az, ps, q, p
    shift = min(diff, 11)
    sticky = int(bool(small & ((1 << shift) - 1)))
    small = (small >> shift) | sticky
    sig = big + small if sign == other else big - small
    if sig == 0:
        return 0
    if sig & 2048:
        sticky |= sig & 1
        sig >>= 1
        e = (e + 1) & 255
    elif not sig & 1024:
        shift = min(11 - sig.bit_length(), e)
        sig = (sig << shift) & 2047
        e -= shift
    frac = (sig >> 3) & 127
    frac += int(bool((sig & 4) and ((sig & 3) or sticky or (sig & 8))))
    if frac == 128:
        frac = 0
        e = (e + 1) & 255
    if e > 254:
        e, frac = 254, 127
    return (sign << 15) | (e << 7) | frac


def sa_fma(a: torch.Tensor, b: torch.Tensor, c: torch.Tensor) -> torch.Tensor:
    av = a.contiguous().view(torch.uint8).tolist()
    bv = b.contiguous().view(torch.uint8).tolist()
    cv = c.contiguous().view(torch.int16).tolist()
    return torch.tensor([fma_bits(x, y, z & 65535) for x, y, z in zip(av,bv,cv)],
                        dtype=torch.uint16).view(torch.bfloat16)


def ipt_row(a: torch.Tensor, weights: torch.Tensor, partial: torch.Tensor) -> torch.Tensor:
    """Default IPT: 32-bit anchor integers, headroom seven, RNE BF16 output."""
    av = a.contiguous().view(torch.uint8).tolist()
    wv = weights.contiguous().view(torch.uint8).tolist()
    pv = partial.contiguous().view(torch.int16).tolist()
    result = []
    for ws, psum in zip(wv, pv):
        psum &= 65535
        products = [product(x,y) for x,y in zip(av,ws)]
        pe, pm = (psum >> 7) & 255, psum & 127
        anchor = max([e - 13 if e else -1024 for _,e,_ in products]
                     + [pe - 127 if (psum & 32767) else -1024]) + 7
        total = 0
        for s, e, m in products:
            if e:
                magnitude = ((128 | m) << 24) >> (anchor - (e - 13))
                total += -magnitude if s else magnitude
        shift = anchor - (pe - 127) - 24
        sig = (128 if pe else 0) | pm
        magnitude = 0 if shift >= 32 or shift < -31 else (sig >> shift if shift >= 0 else (sig << -shift) & 0xffffffff)
        total += -magnitude if psum & 32768 else magnitude
        total = ((total + (1 << 31)) & 0xffffffff) - (1 << 31)
        if not total:
            result.append(0)
            continue
        sign, mag = int(total < 0), abs(total)
        lead = mag.bit_length() - 1
        shift = max(0, lead - 7)
        sig, remainder = mag >> shift, mag & ((1 << shift) - 1)
        if shift and (remainder > (1 << (shift-1)) or (remainder == (1 << (shift-1)) and sig & 1)):
            sig += 1
        if sig >= 256:
            sig >>= 1
            lead += 1
        # int->recFN->exponent adjustment, normal domain of default FP8 inputs.
        exponent = lead + anchor - 31 + 127
        if exponent <= 0:
            bits = 0
        elif exponent >= 255:
            bits = (sign << 15) | 0x7f7f
        else:
            bits = (sign << 15) | (exponent << 7) | (sig & 127)
        result.append(bits)
    return torch.tensor(result, dtype=torch.uint16).view(torch.bfloat16)
