"""Generate DMA-side bandwidth-latency probe programs (the Mess benchmark, for a DMA client).

The Mess benchmark measures a memory system as a family of bandwidth-latency
curves: a pointer-chase probe times single accesses while traffic generators
on other cores hold the memory at a chosen bandwidth and read/write mix. The
Atlas memory client is the DMA engine, so this script writes the same
experiment as baremetal programs: channel 0 issues one 32-byte probe load (or
store) while channels 1..7 stream background transfers with a chosen mix of
loads and stores and a chosen size, which sets the offered bandwidth. The
program banks two cycle counts into CSR_DBG1: the probe's own A-to-D time in
the low 16 bits and the whole traffic phase in the high 16 bits, from which
the delivered background bandwidth follows. Each program is one point; a
sweep of programs is one curve. Run them with ``baremetal/agentic/run_asm_tests.sh``
on VCS (ideally with ``baremetal/dramsim2_ini_norefresh``) or on the bringup
board, then ``scripts/fit_dma_probe_curve.py`` turns the logs into a Mess
curve file for ``CurveMemoryBackend``.

    python scripts/gen_dma_probe_programs.py --out ../baremetal/assembly

Program naming: ``perf_dma_probe_<rd>r_<bg>bg_<size>.S`` where ``rd`` is the
background read percentage (100, 50, 0), ``bg`` the number of background
channels (0..7) and ``size`` the background transfer size in bytes.
"""
from __future__ import annotations

import argparse
from pathlib import Path

HEADER = """# {name}.S — DMA bandwidth-latency probe: {desc}
# Channel 0 times one 32 B {probe} while channels 1..{last} stream {size} B
# transfers ({rd}% loads) as background traffic. CSR_DBG1 = (traffic phase
# cycles << 16) | probe cycles; background bytes = {bg_bytes}.
# Generated by npu-model/scripts/gen_dma_probe_programs.py.
# @TIMEOUT 400000
# @DRAM_BASE 0x90000000
# @PERF_REPORT
"""

# Background DRAM regions are contiguous tiles from here, the way workloads lay
# out their operands (so the background hits DRAM like a real tile stream rather
# than spreading over banks); the probe's own line sits 1 MiB above.
BG_BASE = 0x9000_0000
PROBE_DRAM = 0x9010_0000
PROBE_VMEM_WORD = 0        # VMEM word 0 (line 0)
BG_VMEM_WORD = 2048        # 8 KiB in, 1 KiB (256 words) per channel


def program(rd: int, bg: int, size: int, probe_store: bool, repeats: int) -> str:
    name = f"perf_dma_probe_{rd}r_{bg}bg_{size}" + ("_st" if probe_store else "")
    lines = [HEADER.format(name=name, desc=f"{bg} background channels, {rd}% loads, {size} B",
                           probe="store" if probe_store else "load", last=bg, size=size, rd=rd,
                           bg_bytes=bg * size * repeats)]
    emit = lines.append
    emit("    LI    x5, 0x00000000")
    emit("    DMA.CONFIG x5, 0")
    # Registers: x5 config, x8/x10 probe VMEM/DRAM, x12/x13 sizes, x20-x23 timers,
    # x1..x7 background VMEM words, x24..x30 background DRAM addresses.
    emit("    LI    x12, 32")
    emit(f"    LI    x13, {size}")
    emit(f"    LI    x8, {PROBE_VMEM_WORD}")
    emit(f"    LI    x10, {PROBE_DRAM:#x}")
    # Background: each channel re-issues its transfer `repeats` times so the
    # memory stays loaded for the whole probe. Channels alternate loads and
    # stores to hit the requested mix.
    for ch in range(1, bg + 1):
        emit(f"    LI    x{ch}, {BG_VMEM_WORD + 256 * (ch - 1)}")
        emit(f"    LI    x{23 + ch}, {BG_BASE + max(size, 1024) * (ch - 1):#x}")
    emit("    CSRRS x20, 0xC00, x0        # x20 = traffic phase start")
    emit("    ADDI  x0, x0, 0             # keep CSR reads apart")
    for rep in range(repeats):
        for ch in range(1, bg + 1):
            is_load = (100 * (ch - 1)) // bg < rd       # first ceil(rd%) of the channels load
            if is_load:
                emit(f"    DMA.LOAD  x{ch}, x{23 + ch}, x13, {ch}")
            else:
                emit(f"    DMA.STORE x{23 + ch}, x{ch}, x13, {ch}")
        if rep == 0:
            emit("    CSRRS x21, 0xC00, x0        # x21 = probe issue")
            if probe_store:
                emit("    DMA.STORE x10, x8, x12, 0")
            else:
                emit("    DMA.LOAD  x8, x10, x12, 0")
            emit("    DMA.WAIT  0")
            emit("    CSRRS x22, 0xC00, x0        # x22 = probe done")
            emit("    ADDI  x0, x0, 0             # keep CSR reads apart")
        for ch in range(1, bg + 1):
            emit(f"    DMA.WAIT  {ch}")
    emit("    CSRRS x23, 0xC00, x0        # x23 = traffic phase end")
    emit("    SUB   x22, x22, x21         # probe cycles")
    emit("    SUB   x23, x23, x20         # traffic phase cycles")
    emit("    SLLI  x23, x23, 16")
    emit("    OR    x22, x22, x23")
    emit("    CSRRW x0,  0xC11, x22       # stash in CSR_DBG1")
    emit("    ADDI  x30, x0, 1")
    emit("    CSRW  x30, 0xC10")
    emit("    ECALL")
    return name, "\n".join(lines) + "\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--out", type=Path, required=True, help="Directory for the .S files")
    parser.add_argument("--reads", nargs="*", type=int, default=[100, 50, 0], help="Background read percentages")
    parser.add_argument("--channels", nargs="*", type=int, default=[0, 1, 2, 4, 7], help="Background channel counts")
    parser.add_argument("--sizes", nargs="*", type=int, default=[32, 128, 1024],
                        help="Background transfer bytes; small sizes give moderate loads, 1 KiB saturates")
    parser.add_argument("--repeats", type=int, default=4, help="Background re-issues per channel")
    parser.add_argument("--probe-store", action="store_true", help="Time a store probe instead of a load")
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)
    written = []
    for rd in args.reads:
        for bg in args.channels:
            for size in (args.sizes if bg else [1024]):
                if bg == 0 and rd != args.reads[0]:
                    continue                                   # unloaded point is mix-independent
                # The unloaded point is measured for both probe directions; it anchors
                # the 100 % (load probe) and 0 % (store probe) curves.
                directions = (False, True) if bg == 0 else (args.probe_store,)
                for probe_store in directions:
                    name, text = program(rd, bg, size, probe_store, args.repeats)
                    (args.out / f"{name}.S").write_text(text)
                    written.append(name)
    print("\n".join(written))
    print(f"{len(written)} programs written to {args.out}")


if __name__ == "__main__":
    main()
