class AtlasCtrlSigs(implicit val p: Parameters) extends Bundle {
  // ... signal declarations ...

  def default: List[BitPat] =
    //         valid  br_type  src1  src2  dst  imm  msrc1  msrc2  acc_read  mdst  mem_read  mem_write  acc_write  wb_write  pc  mxu_0_valid  mxu_1_valid  scalar_valid  vpu_valid  xlu_valid  dma_valid  alu_op  vpu_op  xlu_op
    List(N    , BR_X   , X      , X      , X  , IMM_X, X       , X       , X       , X   , N       , N        , N        , N       , X , N          , N          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X)

  def decode(inst: UInt, table: Iterable[(BitPat, List[BitPat])]) = {
    val decoder = DecodeLogic(inst, default, table)
    val sigs = Seq(valid, br_type, src1, src2, dst, imm, msrc1, msrc2, acc_read, mdst, mem_read, mem_write, acc_write, wb_write, pc, mxu_0_valid, mxu_1_valid, scalar_valid, vpu_valid, xlu_valid, dma_valid, alu_op, vpu_op, xlu_op)
    sigs zip decoder map { case (s, d) => s := d }
    this
  }
}

class AtlasDecode(implicit val p: Parameters) extends DecodeConstants {
  // Auto-generated decode table
  // instruction               List(valid, br_type, src1   , src2   , dst, imm  , msrc1   , msrc2   , acc_read, mdst, mem_read, mem_write, acc_write, wb_write, pc, mxu_0_valid, mxu_1_valid, scalar_valid, vpu_valid, xlu_valid, dma_valid, alu_op       , vpu_op              , xlu_op  )
  val table: Array[(BitPat, List[BitPat])] = Array(
    DELAY                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    ADDI                   -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_ADD   , VPU_OP_X            , XLU_OP_X),
    SLLI                   -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_LSHIFT, VPU_OP_X            , XLU_OP_X),
    SLTI                   -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_LT    , VPU_OP_X            , XLU_OP_X),
    SLTIU                  -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_LT    , VPU_OP_X            , XLU_OP_X),
    XORI                   -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_BITXOR, VPU_OP_X            , XLU_OP_X),
    SRLI                   -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_RSHIFT, VPU_OP_X            , XLU_OP_X),
    SRAI                   -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_RSHIFT, VPU_OP_X            , XLU_OP_X),
    ORI                    -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_BITOR , VPU_OP_X            , XLU_OP_X),
    ANDI                   -> List(Y    , BR_N   , OP1_RS1, OP2_IMM, Y  , IMM_I, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_BITAND, VPU_OP_X            , XLU_OP_X),
    ADD                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_ADD   , VPU_OP_X            , XLU_OP_X),
    SUB                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_SUB   , VPU_OP_X            , XLU_OP_X),
    SLL                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_LSHIFT, VPU_OP_X            , XLU_OP_X),
    SLT                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_LT    , VPU_OP_X            , XLU_OP_X),
    SLTU                   -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_LT    , VPU_OP_X            , XLU_OP_X),
    XOR                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_BITXOR, VPU_OP_X            , XLU_OP_X),
    SRL                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_RSHIFT, VPU_OP_X            , XLU_OP_X),
    SRA                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_RSHIFT, VPU_OP_X            , XLU_OP_X),
    OR_                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_BITOR , VPU_OP_X            , XLU_OP_X),
    AND_                   -> List(Y    , BR_N   , OP1_RS1, OP2_RS1, Y  , IMM_X, OP1_MRS1, OP2_MRS2, N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_BITAND, VPU_OP_X            , XLU_OP_X),
    LUI                    -> List(Y    , BR_N   , OP1_IMM, OP2_X  , Y  , IMM_U, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , Y           , N        , N        , N        , ALU_OP_BITAND, VPU_OP_X            , XLU_OP_X),
    JAL                    -> List(Y    , BR_N   , OP1_PC , OP2_IMM, N  , IMM_J, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , Y , N          , N          , Y           , N        , N        , N        , ALU_OP_SUB   , VPU_OP_X            , XLU_OP_X),
    BEQ                    -> List(Y    , BR_EQ  , OP1_RS1, OP2_RS2, N  , IMM_B, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , Y , N          , N          , Y           , N        , N        , N        , ALU_OP_EQ    , VPU_OP_X            , XLU_OP_X),
    BNE                    -> List(Y    , BR_NE  , OP1_RS1, OP2_RS2, N  , IMM_B, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , Y , N          , N          , Y           , N        , N        , N        , ALU_OP_NOTEQ , VPU_OP_X            , XLU_OP_X),
    BLT                    -> List(Y    , BR_LT  , OP1_RS1, OP2_RS2, N  , IMM_B, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , Y , N          , N          , Y           , N        , N        , N        , ALU_OP_LT    , VPU_OP_X            , XLU_OP_X),
    BGE                    -> List(Y    , BR_N   , OP1_RS1, OP2_RS2, N  , IMM_B, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , Y , N          , N          , Y           , N        , N        , N        , ALU_OP_GTE   , VPU_OP_X            , XLU_OP_X),
    BLTU                   -> List(Y    , BR_LT  , OP1_RS1, OP2_RS2, N  , IMM_B, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , Y , N          , N          , Y           , N        , N        , N        , ALU_OP_LT    , VPU_OP_X            , XLU_OP_X),
    BGEU                   -> List(Y    , BR_N   , OP1_RS1, OP2_RS2, N  , IMM_B, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , Y , N          , N          , Y           , N        , N        , N        , ALU_OP_GTE   , VPU_OP_X            , XLU_OP_X),
    MV_MW                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_MRS1, OP2_X   , N       , N   , N       , N        , N        , Y       , N , N          , N          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    MATMUL_MXU0            -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_MRS1, OP2_MRS2, N       , Y   , N       , N        , N        , N       , N , Y          , N          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    MATMUL_MXU1            -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_MRS1, OP2_MRS2, N       , Y   , N       , N        , N        , N       , N , N          , Y          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VADD                   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_ADD          , XLU_OP_X),
    VSUB                   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_SUB          , XLU_OP_X),
    VMUL                   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_MULT         , XLU_OP_X),
    VSQRT                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_SQRT         , XLU_OP_X),
    VRCP                   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_DIV          , XLU_OP_X),
    VEXP                   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_EXP          , XLU_OP_X),
    VLOG2                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_LOG2         , XLU_OP_X),
    VEXP2                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_EXP2         , XLU_OP_X),
    VSIN                   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_SIN          , XLU_OP_X),
    VCOS                   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_COS          , XLU_OP_X),
    VTANH                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_TANH         , XLU_OP_X),
    VREDUCE_SUM            -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VROT_REDUCE_SUM        -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    MV_MM                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_MRS1, OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_READ_MRF_F32 , XLU_OP_X),
    VTRPOSE_H              -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_FLOORDIV     , XLU_OP_X),
    VTRPOSE_L              -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_FLOORDIV     , XLU_OP_X),
    VLOAD                  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , Y       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VSTORE                 -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_MRS2, N       , N   , N       , Y        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATPUSH_WEIGHT_MXU0   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , Y       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATPUSH_WEIGHT_MXU1   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , Y       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATPUSH_ACC_FP8_MXU0  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , Y        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATPUSH_ACC_FP8_MXU1  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , Y        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATPUSH_ACC_BF16_MXU0 -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , Y        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATPUSH_ACC_BF16_MXU1 -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , Y        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATPOP_FP8_ACC_MXU0   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , Y       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_VIEW         , XLU_OP_X),
    VMATPOP_FP8_ACC_MXU1   -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , Y       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_VIEW         , XLU_OP_X),
    VMATPOP_BF16_ACC_MXU0  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , Y       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_READ_ACC_BF16, XLU_OP_X),
    VMATPOP_BF16_ACC_MXU1  -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , Y       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_READ_ACC_BF16, XLU_OP_X),
    VMATPOP_MXU0           -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , Y       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_READ_ACC_BF16, XLU_OP_X),
    VMATPOP_MXU1           -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , Y       , Y   , N       , N        , N        , N       , N , N          , N          , N           , Y        , N        , N        , ALU_OP_X     , VPU_OP_READ_ACC_BF16, XLU_OP_X),
    VMATMUL_MXU0           -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , Y          , N          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATMUL_MXU1           -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , Y          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATMUL_ACC_MXU0       -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , Y          , N          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    VMATMUL_ACC_MXU1       -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , Y          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    DMA_LOAD               -> List(Y    , BR_LT  , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , Y   , Y       , N        , N        , N       , N , N          , N          , N           , N        , N        , Y        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    DMA_LOAD_MXU0          -> List(Y    , BR_LT  , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , Y       , N        , N        , Y       , N , N          , N          , N           , N        , N        , Y        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    DMA_LOAD_MXU1          -> List(Y    , BR_LT  , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , Y       , N        , N        , Y       , N , N          , N          , N           , N        , N        , Y        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    DMA_STORE              -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , Y        , N        , N       , N , N          , N          , N           , N        , N        , Y        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X),
    DMA_WAIT               -> List(Y    , BR_N   , OP1_X  , OP2_X  , N  , IMM_X, OP1_X   , OP2_X   , N       , N   , N       , N        , N        , N       , N , N          , N          , N           , N        , N        , N        , ALU_OP_X     , VPU_OP_X            , XLU_OP_X)
  )
}
